name:                poly-lang
version:             0.2.0
github:              dcastrop/DPoly
license:             BSD3
author:              David Castro-Perez <david.castro.dcp@gmail.com>
maintainer:          David Castro-Perez <david.castro.dcp@gmail.com>
copyright:           2017 David Castro-Perez
extra-source-files:
- README.md
- ChangeLog.md
synopsis:            Deep embedding of a point-free language based on Polynomial
                     functors
# category:            Web
description:         Please see the README on Github at <https://github.com/dcastrop/DPoly#readme>
dependencies:
- base >= 4.9 && < 5
- singletons >= 2.4 && < 2.5
- prettyprinter >= 1.2 && < 1.3
- quoted-prettyprinter >= 0.1 && < 0.2
- mtl >= 2.2.1 && < 2.3
- constrained-control >= 0.1 && < 0.2
- constraints >= 0.10 && < 0.11
- ivector >= 0.1 && < 0.2

library:
  source-dirs: src
  ghc-options:
  - -Wall
