name:                poly-lang
version:             0.2.0
github:              dcastrop/DPoly
license:             BSD3
author:              David Castro-Perez <david.castro.dcp@gmail.com>
maintainer:          David Castro-Perez <david.castro.dcp@gmail.com>
copyright:           2017 David Castro-Perez
extra-source-files:
- README.md
- ChangeLog.md
synopsis:            Deep embedding of a point-free language based on Polynomial
                     functors
# category:            Web
description:         Please see the README on Github at <https://github.com/dcastrop/DPoly#readme>
dependencies:
- base >= 4.7 && < 5
- type-combinators >= 0.2.4 && < 0.3
- singletons >= 2.2 && < 2.4

library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -Werror
